"""Database models and connection for weather arb bot."""
from datetime import datetime
from typing import Optional
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

from weatherbot.config import settings

engine = create_engine(
    settings.DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in settings.DATABASE_URL else {}
)
# expire_on_commit=False so ORM objects stay readable after their session
# closes — settle_live_trades/settle_paper_trades return Trade rows that the
# scheduler reads (result, pnl) post-commit. Without this, the commit expires
# those attributes and the first read raises DetachedInstanceError.
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine, expire_on_commit=False)
Base = declarative_base()


class Signal(Base):
    """Trading signals generated by the bot."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    market_type = Column(String, default="weather", index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    direction = Column(String)
    model_probability = Column(Float)
    market_price = Column(Float)
    edge = Column(Float)
    confidence = Column(Float)

    kelly_fraction = Column(Float)
    suggested_size = Column(Float)

    sources = Column(JSON)
    reasoning = Column(String)

    executed = Column(Boolean, default=False)

    # Calibration tracking — filled after settlement
    actual_outcome = Column(String, nullable=True)    # "up" or "down" — actual market result
    outcome_correct = Column(Boolean, nullable=True)   # did our direction prediction match?
    settlement_value = Column(Float, nullable=True)     # 1.0=UP won, 0.0=DOWN won
    settled_at = Column(DateTime, nullable=True)        # when we recorded the outcome


class ScanLog(Base):
    """Log of each market scan run."""
    __tablename__ = "scan_logs"

    id = Column(Integer, primary_key=True, index=True)
    run_id = Column(String, unique=True, index=True)
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    categories_scanned = Column(JSON)
    platforms_scanned = Column(JSON)

    markets_found = Column(Integer, default=0)
    signals_generated = Column(Integer, default=0)
    trades_executed = Column(Integer, default=0)

    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)


def init_db():
    """Initialize database tables."""
    Base.metadata.create_all(bind=engine)


def get_db():
    """Get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
